django/core/urls.py
from django.urls import path


urlpatterns = [

]

django/investimento/urls.py
from django.urls import path, include
from investimento.views import investimento_cadastro, investimento_lista, investimento_detalhe, retirada_lista, sem_falsos_verdadeiros

urlpatterns = [
    #   Investimento
    path('cadastro/', investimento_cadastro, name="investimento_cadastro"),
    path('lista/', investimento_lista, name="investimento_lista"),
    path('detail/<int:pk>/', investimento_detalhe, name="investimento_detalhe"),

    #   Retiradas
    path('retiradas/lista/', retirada_lista, name='retirada_lista'),

    path('treino_task/', sem_falsos_verdadeiros, name="treino_task"),
]

django/projeto/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import routers

from core.views import index_view
from usuario.views import signup_usuario_view
from publico.views import publico_index_view

router = routers.DefaultRouter()

urlpatterns = [

    #   DJANGO
    path('admin/', admin.site.urls,),

    #   DEBUG
    path('__debug__/', include('debug_toolbar.urls')),

    #   API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    #   PUBLICO
    path('', publico_index_view, name='publico_index_view'),

    #   INTERNO
    path('dashboard/', index_view, name='index_interno'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', signup_usuario_view, name='signup'),

    path('usuario/', include('usuario.urls')),
    path('administracao/', include('usuario.urls')),
    path('investimento/', include('investimento.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/investimento/models.py
from django.db import models
from datetime import date
from decimal import Decimal
from django.dispatch import receiver
from django.utils.timezone import now
from usuario.models import UsuarioModel
from django.db.models.signals import post_save
from functions.investimento import calculo_retirada, calculo_saldo
from functions.tempo import diferenca_tempo
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


class InvestimentoModel(models.Model):
    proprietario = models.ForeignKey(UsuarioModel, on_delete=models.DO_NOTHING)
    valor_investido = models.DecimalField(
        'Valor investido', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    data_investimento = models.DateField(
        'Data do investimento', default=now,
        validators=[
            #   Impede datas futuras
            MaxValueValidator(limit_value=date.today)
        ]
    )
    meses_de_investimento = models.PositiveIntegerField(
        'Meses de investimento', null=True, blank=True
    )

    #  False = Já retirado, True = Ainda aberto
    status = models.BooleanField('Status', default=True)

    class Meta:
        db_table = 'investimento'
        verbose_name = 'Investimento'
        verbose_name_plural = 'Investimentos'
        ordering = ('-pk',)

    def __str__(self):
        return 'Id: {} - Valor: {}'.format(self.pk, self.valor_investido)

    def save(self, *args, **kwargs):
        try:
            anos, meses, dias = diferenca_tempo(self.data_investimento)
            self.meses_de_investimento = meses

            return super().save(*args, **kwargs)
        except Exception as e:
            print('>>> Investimento.models.InvestimentoModel: {}'.format(e))
            return e


#   Quando o insert é feito nos investimentos dispara uma função e calcula coisas como o saldo.
#   Então aplica no campo, na tabela de usuário
@receiver(post_save, sender=InvestimentoModel)
def investimento_post_save_receiver(sender, instance, **kwargs):

    usuario = instance.proprietario.pk
    saldo_b, saldo_l = calculo_saldo(
        InvestimentoModel.objects.filter(
            proprietario=usuario,
            status=True
        )
    )

    usuario_tb = UsuarioModel.objects.get(
        pk=usuario
    )
    usuario_tb.saldo = saldo_b
    usuario_tb.save()


class RetiradaModel(models.Model):
    investimento = models.OneToOneField(InvestimentoModel, on_delete=models.DO_NOTHING)
    data_retirada = models.DateField(
        default=now,
        validators=[
            MaxValueValidator(limit_value=date.today),
        ]
    )

    taxa_ganho = models.DecimalField(
        'Taxa de ganho', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    taxa_tributo = models.DecimalField(
        'Taxa de tributo', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    imposto = models.DecimalField(
        'Imposto', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    lucro_bruto = models.DecimalField(
        'Lucro bruto', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    lucro_liquido = models.DecimalField(
        'Lucro líquido', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    valor_final_b = models.DecimalField(
        'Valor de retorno bruto', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )
    valor_final_l = models.DecimalField(
        'Valor de retorno líquido', max_digits=15, decimal_places=2,
        validators=[
            #   Impede valor menor que 0
            MinValueValidator(Decimal('0.00'))
        ]
    )

    class Meta:
        db_table = 'retirada'
        verbose_name = 'Retirada'
        verbose_name_plural = 'Retiradas'
        ordering = ('-pk',)

    def __str__(self):
        return 'ID: {} - INVESTIMENTO: {} - DATA DE RETIRADA: {}'.format(
            self.pk, self.investimento.pk, self.data_retirada.strftime('%d/%m/%Y'))

    #   TODO: corrigir - exibir o erro para o campo e não para o form
    def clean(self):
        if self.data_retirada < self.investimento.data_investimento:
            raise ValidationError('A data de retirada não pode ser anterior à data de investimento')
        return super().clean()

    def save(self, *args, **kwargs):
        try:
            #   Método save reescrito para que apenas receba o id do investimento e a data
            #   em que está sendo feito a retirada. Tendo esses dados, ele já calcula todas
            #   as outras informações e salva na tabela de forma automatica.

            # Se for um INSERT
            if not self.pk:

                dados = calculo_retirada(
                    self.investimento.valor_investido,
                    self.investimento.data_investimento
                )

                self.taxa_ganho = dados['taxa_ganho']
                self.taxa_tributo = dados['taxa_tributo']
                self.imposto = dados['imposto']
                self.lucro_bruto = dados['lucro_bruto']
                self.lucro_liquido = dados['lucro_liquido']
                self.valor_final_b = dados['valor_final_b']
                self.valor_final_l = dados['valor_final_l']

            # Se for um UPDATE
            else:
                pass
            return super().save(*args, **kwargs)
        except Exception as e:
            print('>>> Investimento.models.RetiradaModel: {}'.format(e))
            return e


@receiver(post_save, sender=RetiradaModel)
def retirada_post_save_receiver(sender, instance, **kwargs):
    try:
        #   Quando o insert é feito nas retiradas dispara uma função onde calcula o saldo e aplica
        #   na tabela de usuário e muda o status do investimento para False.

        usuario = instance.investimento.proprietario.pk
        investimento = instance.investimento.pk

        investimento_tb = InvestimentoModel.objects.get(
            pk=investimento
        )
        investimento_tb.status = False
        investimento_tb.save()

        saldo_b, saldo_l = calculo_saldo(
            InvestimentoModel.objects.filter(
                proprietario=usuario,
                status=True
            )
        )

        usuario_tb = UsuarioModel.objects.get(
            pk=usuario
        )
        usuario_tb.saldo = saldo_b
        usuario_tb.save()
    except Exception as e:
        print('>>> Investimento.models.RetiradaModel__post_save: {}'.format(e))

django/investimento/forms.py
from django.forms import ModelForm
from investimento.models import InvestimentoModel, RetiradaModel


class InvestimentoCadastroForm(ModelForm):
    class Meta:
        model = InvestimentoModel
        fields = [
            'valor_investido',
            'data_investimento',
        ]


class RetiradaCadastroForm(ModelForm):
    class Meta:
        model = RetiradaModel
        fields = [
            'investimento',
            'data_retirada',
        ]

django/investimento/views.py
from django.views.generic import CreateView, ListView, DetailView
from investimento.models import InvestimentoModel, RetiradaModel
from django.contrib.auth.mixins import LoginRequiredMixin
from investimento.forms import InvestimentoCadastroForm
from django.shortcuts import get_object_or_404

from django.urls import reverse_lazy
from django.http import HttpResponse


class InvestimentoCadastroView(LoginRequiredMixin, CreateView):
    template_name = 'investimento/investimento_cadastro.html'
    model = InvestimentoModel
    form_class = InvestimentoCadastroForm
    success_url = reverse_lazy('investimento_lista')

    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            self.object.proprietario_id = self.request.user.pk
            self.object.save()
        except Exception as e:
            print('Erro: {}'.format(e))
        finally:
            return super(InvestimentoCadastroView, self).form_valid(form)


class InvestimentoListaView(LoginRequiredMixin, ListView):
    template_name = 'investimento/investimento_lista.html'
    model = InvestimentoModel

    def get_queryset(self):
        #   Pega o ID do usuário e filtra apenas seus investimentos
        return InvestimentoModel.objects.filter(
            proprietario=self.request.user.pk
        )


class InvestimentoDetalheView(LoginRequiredMixin, DetailView):
    template_name = 'investimento/investimento_detalhe.html'
    model = InvestimentoModel


class RetiradaListaView(LoginRequiredMixin, ListView):
    template_name = 'investimento/investimento_retirada_lista.html'
    model = RetiradaModel

    def get_queryset(self):
        #   Pega o ID do usuário e filtra apenas suas retiradas
        return RetiradaModel.objects.filter(investimento__proprietario=self.request.user.pk)


def retiradaCadastroView(request, investimento):
    context = {}

    try:
        ...
    except:
        ...
    finally:
        ...


def sem_falsos_verdadeiros():
    #   Pega todos os dados que já possuem retirada registrada mas que o status manteve True,
    #   depois faz a alteração do status para False

    try:
        investimentos = InvestimentoModel.objects.filter(status=True).order_by('pk')

        objetos_falhos = RetiradaModel.objects.filter(investimento__in=investimentos)
        for o in objetos_falhos:
            objeto = get_object_or_404(InvestimentoModel, pk=o.investimento.pk)
            objeto.status = False
            objeto.save()
        return HttpResponse(status=200)
    except Exception as e:
        print('>>> investimento.views__treino_task: {}'.format(e))
        return e


investimento_cadastro = InvestimentoCadastroView.as_view()
investimento_lista = InvestimentoListaView.as_view()
investimento_detalhe = InvestimentoDetalheView.as_view()
retirada_lista = RetiradaListaView.as_view()

django/templates/investimento/investimento_cadastro.html
{% extends 'base/base_interno.html' %}
{% load static %}
{% load widget_tweaks %}


{% block baseInterno %}
<div class="row mt-5">
    <div class="col-xxl-3 col-xl-3 col-lg-3 col-md-6 col-sm-12 col-xs-12 mt-2">
        <h3>Cadastro de investimento</h3>

        
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}


        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_valor_investido">Valor investido:</label>
                {{ form.valor_investido|add_class:"form-control" }}
                <small class="mt-1 text-danger">{{ form.valor_investido.errors }}</small>
            </div>
            <div class="form-group">
                <label for="id_data_investimento">Data do investimento:</label>
                {{ form.data_investimento|add_class:"form-control" }}
                <small class="mt-1 text-danger">{{ form.data_investimento.errors }}</small>
            </div>

            <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
        </form>
    </div>
</div>
{% endblock baseInterno %}

django/templates/investimento/investimento_detalhe.html
{% extends 'base/base_interno.html' %}
{% load static %}


{% block baseInterno %}

{% if object.status %}
<div class="row mt-5">
    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#retirarModal">
        Retirar
        <i class="fas fa-plus-circle"></i>
    </a>
</div>


<div class="modal fade" id="retirarModal" tabindex="-1" role="dialog" aria-labelledby="retirarModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="retirarModalLabel">Deseja realmente retirar o investimento?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Selecione "Retirar" abaixo se você está pronto pra encerrar o investimento.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-success" href="#">Retirar</a>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="row mt-5">
    <div class="col-12">
        <h3 class="mb-3">Detalhe do investimento</h3>
        <table class="table table-striped table-bordered">
            <tr>
                <td>Id</td>
                <td>{{ object.pk }}</td>
            </tr>
            <tr>
                <td>Proprietário</td>
                <td>{{ object.proprietario }}</td>
            </tr>
            <tr>
                <td>Valor investido</td>
                <td>{{ object.valor_investido }}</td>
            </tr>
            <tr>
                <td>Data do investimento</td>
                <td>{{ object.data_investimento }}</td>
            </tr>
            <tr>
                <td>Meses de investimento</td>
                <td>{{ object.meses_de_investimento }}</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>
                    {% if object.status %}
                    Aberto
                    {% else %}
                    Já retirado
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
</div>
<hr>
{% endblock baseInterno %}

django/templates/investimento/investimento_lista.html
{% extends 'base/base_interno.html' %}
{% load static %}


{% block injectCSS %}
<link href="{% static 'lib/sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock injectCSS %}


{% block injectJS %}
<!-- Page level plugins -->
<script src="{% static 'lib/sb-admin-2/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#tabela_investimento').DataTable({
            language: {
                url: "{% static 'lib/sb-admin-2/vendor/datatables/pt-br.json' %}"
            }
        });
        $('table tr').click(function () {
            window.location = $(this).data('href');
            return false;
        });
    });
</script>
{% endblock injectJS %}


{% block baseInterno %}
<div class="row mt-5">
    <a href="{% url 'investimento_cadastro' %}" class="btn btn-primary">
        Novo investimento
        <i class="fas fa-plus-circle"></i>
    </a>
</div>
<div class="row mt-5">
    <div class="col-12">
        <h3 class="mb-3">Meus investimentos</h3>
        <div class="table-responsive">
            <table id="tabela_investimento" class="table table-sm table-hover table-striped table-bordered">
                <thead class="thead-dark">
                    <th scope="col" class="text-center">ID</th>
                    <th scope="col" class="text-center">PROPRIETÁRIO</th>
                    <th scope="col" class="text-center">VALOR INVESTIDO</th>
                    <th scope="col" class="text-center">DATA DO INVESTIMENTO</th>
                    <th scope="col" class="text-center">MESES DE INVESTIMENTO</th>
                    <th scope="col" class="text-center">STATUS</th>
                </thead>
                <tbody>
                    {% for investimento in object_list %}

                    <tr data-href="{% url 'investimento_detalhe' investimento.pk %}">
                        <th class="text-center" scope="row">{{ investimento.pk }}</th>
                        <td class="text-center">
                            ({{investimento.proprietario.pk }})
                            {{ investimento.proprietario.get_short_name }}
                        </td>
                        <td class="text-center">{{ investimento.valor_investido }}</td>
                        <td class="text-center">{{ investimento.data_investimento }}</td>
                        <td class="text-center">{{ investimento.meses_de_investimento }}</td>
                        {% if investimento.status %}
                        <td class="text-center">Aberto</td>
                        {% else %}
                        <td class="text-center">Já retirado</td>
                        {% endif %}
                    </tr>
                    </a>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="5" style="text-align:right">Total:</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<hr>
{% endblock baseInterno %}

django/templates/investimento/investimento_retirada_lista.html
{% extends 'base/base_interno.html' %} {% load static %} {% block injectCSS %}
<link href="{% static 'lib/sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
{% endblock injectCSS %}
{% block injectJS %}
<!-- Page level plugins -->
<script src="{% static 'lib/sb-admin-2/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#tabela_retirada").DataTable({
            language: {
                url: "{% static 'lib/sb-admin-2/vendor/datatables/pt-br.json' %}",
            },
        });
    });
</script>
{% endblock injectJS %}
{% block baseInterno %}
<div class="row mt-5">
    <div class="col-12">
        <h3 class="mb-3">Minhas retiradas</h3>
        <div class="table-responsive">
            <table id="tabela_retirada" class="table table-sm table-hover table-striped table-bordered">
                <thead class="thead-dark">
                    <th scope="col" class="text-center">ID</th>
                    <th scope="col" class="text-center">INVESTIMENTO</th>
                    <th scope="col" class="text-center">PROPRIETÁRIO</th>
                    <th scope="col" class="text-center">DATA DE RETIRADA</th>
                    <th scope="col" class="text-center">TAXA DO GANHO</th>
                    <th scope="col" class="text-center">TAXA DE IMPOSTO</th>
                    <th scope="col" class="text-center">VALOR DO IMPOSTO</th>
                    <th scope="col" class="text-center">LUCRO BRUTO</th>
                    <th scope="col" class="text-center">LUCRO LÍQUIDO</th>
                    <th scope="col" class="text-center">VALOR FINAL BRUTO</th>
                    <th scope="col" class="text-center">VALOR FINAL LÍQUIDO</th>

                </thead>
                <tbody>
                    {% for retirada in object_list %}
                    <tr>
                        <th class="text-center" scope="row">{{ retirada.pk }}</th>
                        <td class="text-center">{{ retirada.investimento.pk }}</td>
                        <td class="text-center">
                            ({{ retirada.investimento.proprietario.pk }})
                            {{ retirada.investimento.proprietario.get_short_name }}
                        </td>
                        <td class="text-center">{{ retirada.data_retirada }}</td>
                        <td class="text-center">{{ retirada.taxa_ganho }} %</td>
                        <td class="text-center">{{ retirada.taxa_tributo }} %</td>
                        <td class="text-center">{{ retirada.imposto }}</td>
                        <td class="text-center">{{ retirada.lucro_bruto }}</td>
                        <td class="text-center">{{ retirada.lucro_liquido }}</td>
                        <td class="text-center">{{ retirada.valor_final_b }}</td>
                        <td class="text-center">{{ retirada.valor_final_l }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr />
{% endblock baseInterno %}