django/core/urls.py
from django.urls import path


urlpatterns = [

]

django/projeto/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import routers

from core.views import index_view
from usuario.views import signup_usuario_view
from publico.views import publico_index_view

router = routers.DefaultRouter()

urlpatterns = [

    #   DJANGO
    path('admin/', admin.site.urls,),

    #   DEBUG
    path('__debug__/', include('debug_toolbar.urls')),

    #   API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    #   PUBLICO
    path('', publico_index_view, name='publico_index_view'),

    #   INTERNO
    path('dashboard/', index_view, name='index_interno'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', signup_usuario_view, name='signup'),

    path('usuario/', include('usuario.urls')),
    path('administracao/', include('usuario.urls')),
    path('investimento/', include('investimento.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/usuario/urls.py
from django.urls import path
from usuario.views import usuario_perfil, usuario_update, usuario_mudar_senha
from usuario.views import usuario_list_view


urlpatterns = [
    path('perfil/', usuario_perfil, name='perfil'),
    path('usuarios/', usuario_list_view, name='usuario_list'),
    path('alterar-dados/', usuario_update, name='alterar_dados'),
    path('alterar-senha/', usuario_mudar_senha, name='alterar_senha'),
]

django/usuario/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from core.models import EnderecoModel
from django.core.exceptions import ValidationError
from functions.validacao import cpf_ou_cnpj


def validate_cpf_cnpj(value):

    status, texto, documento = cpf_ou_cnpj(value)

    if status:
        return documento
    else:
        raise ValidationError(texto)


class UsuarioManager(BaseUserManager):

    def create_user(self, email, nome, cpf_cnpj, password=None):
        if not email:
            raise ValueError('User must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, nome=nome, cpf_cnpj=cpf_cnpj)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, nome, cpf_cnpj, password):
        user = self.create_user(email, nome, cpf_cnpj, password)
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user


class UsuarioModel(AbstractBaseUser, PermissionsMixin):

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome', 'cpf_cnpj']

    email = models.EmailField('E-Mail', unique=True)
    nome = models.CharField('Nome', max_length=255, blank=True, null=True)
    cpf_cnpj = models.CharField(
        'CPF/CNPJ', max_length=18, unique=True, validators=[validate_cpf_cnpj]
    )
    foto_perfil = models.ImageField(
        upload_to='usuario/user_profile/',
        max_length=100,
        null=True,
        blank=True
    )

    saldo = models.DecimalField(
        'Saldo',
        decimal_places=2,
        max_digits=15,
        default=0.0,
        blank=False,
        null=False
    )

    # PERMISSÕES
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    is_superuser = models.BooleanField('Superusuário', default=False)
    is_anonymous = models.BooleanField('Anonimo', default=False)
    is_trusty = models.BooleanField('E-Mail confirmado', default=False)

    class Meta:
        app_label = 'usuario'
        db_table = 'usuario'
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.email or self.get_short_name()

    def get_full_name(self):
        return str(self.nome)

    def get_short_name(self):
        return str(self.nome).split(" ")[0]

    def email_user(self, subject, message, from_email=None):
        try:
            send_mail(subject, message, from_email, [self.email])
        except Exception as e:
            print('>>> Usuario.models.RetiradaModel__email_user: {}'.format(e))

    def save(self, *args, **kwargs):
        try:
            # Se for um INSERT
            if not self.pk:
                return super().save(*args, **kwargs)

            #   Se for um UPDATE
            else:
                return super().save(*args, **kwargs)
        except Exception as e:
            print('>>> Usuario.models.RetiradaModel__save: {}'.format(e))

django/usuario/forms.py
from django.contrib.auth import forms
from usuario.models import UsuarioModel
from django.forms import ModelForm


class UsuarioCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = UsuarioModel
        fields = [
            'email',
            'password1',
            'password2',
            'nome',
            'cpf_cnpj'
        ]


class UsuarioChangeForm(ModelForm):
    class Meta:
        model = UsuarioModel
        fields = [
            'nome',
            'cpf_cnpj'
        ]


class UsuarioSignUpForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = UsuarioModel
        fields = [
            'email',
            'password1',
            'password2',
            'nome',
            'cpf_cnpj',
        ]


class UsuarioUpdateForm(ModelForm):
    class Meta:
        model = UsuarioModel
        fields = [
            'nome',
            'cpf_cnpj',
            'foto_perfil',
        ]

django/usuario/views.py
import re
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, FormView
from django.contrib.auth.forms import PasswordChangeForm
from usuario.forms import UsuarioSignUpForm, UsuarioUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from functions.investimento import calculo_retirada
from usuario.models import UsuarioModel


class UsuarioSignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = UsuarioSignUpForm
    model = UsuarioModel
    success_url = reverse_lazy('login')


class UsuarioPerfilView(LoginRequiredMixin, DetailView):
    template_name = 'usuario/usuario_detail.html'
    model = UsuarioModel

    def get_object(self):
        return self.request.user


class UsuarioUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'usuario/usuario_update.html'
    model = UsuarioModel
    form_class = UsuarioUpdateForm
    success_url = reverse_lazy('perfil')

    def get_object(self):
        return self.request.user


class UsuarioMudarSenhaView(LoginRequiredMixin, FormView):
    template_name = 'usuario/senha_update.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('perfil')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UsuariosListView(LoginRequiredMixin, ListView):
    template_name = 'administracao/usuarios.html'
    model = UsuarioModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# def calcular_saldos():

#     try:
#         saldo_b, saldo_l = calculo_saldo(
#             InvestimentoModel.objects.filter(
#                 proprietario=usuario,
#                 status=True
#             )
#         )
#     except Exception as e:
#         print('>>> investimento.views__calcular_saldo: {}'.format(e))
#         return e


usuario_list_view = UsuariosListView.as_view()
signup_usuario_view = UsuarioSignUpView.as_view()
usuario_perfil = UsuarioPerfilView.as_view()
usuario_update = UsuarioUpdateView.as_view()
usuario_mudar_senha = UsuarioMudarSenhaView.as_view()

django/templates/usuario/senha_update.html
{% extends 'base/base_interno.html' %}
{% load static %}
{% load widget_tweaks %}


{% block baseInterno %}
<div class="row mt-5">
    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}
    <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 mt-2">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_old_password">Senha antiga:</label>
                {{ form.old_password|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="id_new_password1">Nova senha:</label>
                {{ form.new_password1|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="id_new_password2">Confirmar nova senha:</label>
                {{ form.new_password2|add_class:"form-control" }}
            </div>

            <button type="submit" class="btn btn-primary btn-block">Alterar</button>
        </form>
    </div>
</div>
{% endblock baseInterno %}

django/templates/usuario/usuario_detail.html
{% extends 'base/base_interno.html' %}
{% load static %}


{% block baseInterno %}
<div class="row mt-5">
    <div class="col-xxl-8 col-xl-8 col-lg-6 col-md-12 col-sm-12 col-xs-12 mt-2">
        <h3>Detalhe de usuário</h3>
        <a href="{% url 'alterar_dados' %}" role="button" class="btn btn-primary">Alterar dados</a>
        <div class="table-responsive">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>Cód.</td>
                        <td>{{ user.pk }}</td>
                    </tr>
                    <tr>
                        <td>E-Mail</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>Nome:</td>
                        <td>{{ user.nome }}</td>
                    </tr>
                    <tr>
                        <td>CPF/CNPJ</td>
                        <td>{{ user.cpf_cnpj }}</td>
                    </tr>
                    
                    <tr>
                        <td>Saldo</td>
                        <td>{{ user.saldo }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<tr>
    <td></td>
    <td>{{ user.foto_perfil }}</td>
</tr>
{% endblock baseInterno %}

django/templates/usuario/usuario_update.html
{% extends 'base/base_interno.html' %}
{% load static %}
{% load widget_tweaks %}


{% block injectJS %}
<script src="{% static 'src/js/mascara.js' %}"></script>
{% endblock injectJS %}

{% block baseInterno %}
<div class="row mt-5">
    <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12 mt-2">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% endif %}
            <div class="form-group">
                <label for="id_nome">Nome completo:</label>
                {{ form.nome|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="id_cpf_cnpj">CPF/CNPJ:</label>
                {{ form.cpf_cnpj|add_class:"form-control"|attr:"onpaste:return false" | attr:"ondrop:return false" }}
            </div>
            <div class="form-group">
                <label for="id_foto_perfil">Foto de perfil:</label>
                {{ form.foto_perfil|add_class:"form-control" }}
            </div>

            <button type="submit" class="btn btn-primary btn-block">Alterar</button>
        </form>
    </div>
</div>
{% endblock baseInterno %}